[workspace]
members = [".", "hamego-core", "hamego-wasm"]
resolver = "2"

[workspace.dependencies]
embedded-io-async = "0.7"

[package]
name = "hamego"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-io-async.workspace = true
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
hamego-core = { path = "hamego-core" }
embassy-executor = { version = "0.10", features = ["platform-std", "executor-thread"] }
embassy-sync = { version = "0.8" }
critical-section = { version = "1", features = ["std"] }
